import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [longUrl, setLongUrl] = useState('');
  const [shortURL, setShortURL] = useState('')
  const [error, setError] = useState(false)
  const [loading, setLoading] = useState(false)

  const regex = /[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/i;

  function handleSubmit(event) {
    event.preventDefault()
    if (regex.test(longUrl)) {
      setError(false)
      fetch('http://localhost:3000/api/url', {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ longUrl: longUrl })
      }).then(function (response) {
        return response.text();
      }).then(function (data) {
        setShortURL(data)
      })
    } else {
      setError(true)
    }
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>
        <label htmlFor="url">Long Url:</label>
        <input id="url" type="text" onChange={(event) => { setLongUrl(event.target.value) }} value={longUrl} />
        <br />
        {error ? 'Fix the url' : ''}
        <br />
        {shortURL}
        <button className="hover:bg-gray-400" onClick={handleSubmit} >Submit</button>
      </form>
    </div >
  )
}
